name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
  workflow_dispatch:

jobs:
  scenario:
    name: Scenario ${{ matrix.scenario }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - common-build
          - common-absolute-build
          - grid-build
          - grid-nested-in-venv
          - grid-nested-in-virtualenv
          - testtools-case
          - codegen-case
          # - common-embed
          - common-install
          - grid-install
          # - grid-no-network
          # - grid-partial-install
          - grid-shared-libs

    steps:
    - name: Checking out the PDELab repository
      uses: actions/checkout@v2
      with:
        submodules: true

    # In the future, this can be set up to test an array of Python versions, but
    # there is no gain in doing so right now.
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libopenmpi-dev openmpi-bin

    - name: Run the scenario script
      run: |
        ./testcases/${{ matrix.scenario }}/install.sh
